### ISSUE TITLE
Cooperation Logos

### ISSUE THREAD

**Issue by AnjaB93** [fsiwi-hka/iwi-website#89]
The exxeta and gameforge cooperation logos are too big and not in the actual design. 
Since new logos need to be added in the future, it would be great if the logos are smaller.

Currently:
<img width="776" alt="Bildschirmfoto 2021-10-25 um 13 00 16" src="https://user-images.githubusercontent.com/51286604/138683974-277a0e4b-1310-49ba-81c1-c02800127553.png">

Expected:
<img width="686" alt="Bildschirmfoto 2021-10-25 um 13 01 40" src="https://user-images.githubusercontent.com/51286604/138684189-34461542-0b9e-4b00-92e7-6ac2729e6cfe.png">
r.

**Comment by Blizzardcool** [comment]
Reopened the issue because it is not fixed yet.

**Comment by daniel-vera-g** [comment]
I briefly looked into it and the production/development styles are effectively different.
I assume, something in the `next build` cleans some styles out. Nevertheless, I hadn't the time to look into it further. Would be good to sort it out before adapting designs further.

After a quick search I found:
https://github.com/vercel/next.js/discussions/15053#discussioncomment-143240

Maybe it helps. Let me know, If you need more context.
